image:
  repository: ghcr.io/onurbalmeida/k8s-cleanup
  tag: ""
  pullPolicy: IfNotPresent

schedule: "0 2 * * *"

args:
  dryRun: true
  olderThan: "24h"
  kinds: ["pod","job"]
  allNamespaces: true
  namespace: ""
  excludeNamespaces: ["kube-system","kube-public","local-path-storage"]
  labelSelector: ""
  fieldSelector: ""
  completed: true
  failed: true
  evicted: true
  protect: "keep=true"
  concurrency: 10
  output: "text"
  auditFile: ""
  exitNonZeroOnChanges: false
  logLevel: "info"
  extra: []

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
